spring:
  profiles:
    active: local
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: topics-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: tasks-events-listener-group
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


#spring:
#  config:
#    activate:
#      on-profile: prod
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: library-events-listener-group